apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://<kubernetes-api-server-url>
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: ""
current-context: my-context
